name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    name: deploy to staging
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
       submodules: recursive
    - name: Check is not released
      run: |
        if [ -d "/opt/builds/${{ github.sha }}" ]
        then
            echo "Directory /opt/builds/${{ github.sha }} exists."
            throw "Error: Directory /opt/builds/${{ github.sha }} exists."
        fi
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Package all
      run: |
        Tools/package_server_build.py -p win-x64 linux-x64
        Tools/package_client_build.py

    - name: Update Build Info
      run: Tools/gen_build_info.py

    - name: Shuffle files around
      run: |
        mkdir "release/${{ github.sha }}"
        mv release/*.zip "release/${{ github.sha }}"
    - name: Shuffle files around
      run: |
        mkdir "/opt/builds/${{ github.sha }}"
        mv release/* "/opt/builds/${{ github.sha }}"
    - name: push_to_cdn
      run: "curl -X POST -d \"\" -H 'Authorization: Bearer ${{ secrets.CDN_TOKEN }}' http://localhost:5001/control/update"
    - name: update minifest.json
      run: "python3 /opt/push.py"
